name: generate animation

on:
  # 自動トリガー
  schedule:
    - cron: "*/1 * * * *"
  # 手動トリガー
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  # 権限、環境設定
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # チェックアウト
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # snake.svgの生成
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            img/github-contribution-grid-snake.svg
      
      # SVGファイルの変更を確認し、コミット&プッシュ
      - name: Commit and push the generated SVG if changed
        run: |
          # Gitの設定
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # ファイルの変更確認と処理
          if ! git diff --quiet img/github-contribution-grid-snake.svg; then
            echo "Changes detected, committing and pushing updates..."
            git add img/github-contribution-grid-snake.svg
            git commit -m "Update github-contribution-grid-snake.svg"
            git push
          else
            echo "No changes detected, skipping commit."
          fi
