name: generate animation

on:
  # 自動トリガー
  schedule:
    - cron: "0 0 * * *"
  # 手動トリガー
  workflow_dispatch:
  push:
    branches:
    - "*"

jobs:
  # 権限、環境設定
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # チェックアウト
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # snake.svgの生成
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            img/github-contribution-grid-snake.svg
      
      # SVGファイルのコミット&プッシュ
      - name: Debug and commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # ファイルの存在確認
          echo "Checking if the file exists..."
          if [ -f img/github-contribution-grid-snake.svg ]; then
            echo "File exists. Showing its details:"
            ls -l img/github-contribution-grid-snake.svg
          else
            echo "File not found! Exiting..."
            exit 1
          fi

          # ファイル内容の確認
          echo "Checking file content:"
          cat img/github-contribution-grid-snake.svg || echo "No content found"

          # ファイルの変更確認
          git diff --exit-code img/github-contribution-grid-snake.svg
          if [ $? -ne 0 ]; then
            git add img/github-contribution-grid-snake.svg
            git commit -m "Update github-contribution-grid-snake.svg"
            git push https://***@github.com/koot0303/koot0303.git
          else
            echo "No changes detected, skipping commit."

